version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    network_mode: "host"
    ports:
      - "80:80"
      - "10000:10000"
      - "3306:3306"
    volumes:
      - ./www:/var/www/
      - ./config/sites-enabled.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./config/apache2.conf:/etc/apache2/apache2.conf
      - ./config/php.ini:/etc/php5/apache2/php.ini
      - ./moodledata:/opt/moodle/moodledata

  mysql:
    network_mode: service:web
    depends_on:
      - web
    image: mysql:5.6
    volumes:
      - ./mysql-data/:/var/lib/mysql/
      - ./config/mysql-conf.d/:/etc/mysql/conf.d
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=test

  dns_server:
    build:
      context: .
      dockerfile: Dockerfile-dnsmasq
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config/dnsmasq.conf:/etc/dnsmasq.conf
